### ISSUE TITLE
Not injecting on all files for the first time

### ISSUE THREAD

**Issue by suhailkc** [meeroslav/gulp-inject-partials#11]
`gulp.task('injectPartial', function () {
  return gulp.src("./**/*.html", { base: "./" })
    .pipe(injectPartials())
    .pipe(gulp.dest("."));
});`

it skips some files inject for the first time. but the second time rest of files injected with some extra lines between partial tags.

Why it's not injecting on all files for the first time?

**Comment by meeroslav** [comment]
That's odd. I would have to check. Do you have some minimal repository where I can reproduce this?

**Comment by suhailkc** [comment]
I have fixed it by give specific path.

`gulp.task('injectPartial', function () {`
`   var injPartial1 =  gulp.src("./pages/**/*.html", { base: "./" })`
`      .pipe(injectPartials())`
`      .pipe(gulp.dest("."));`
`    var injPartial2 =  gulp.src("./*.html", { base: "./" })`
`      .pipe(injectPartials())`
`      .pipe(gulp.dest("."));`
`    return merge(injPartial1, injPartial2);`
`  });`
