### ISSUE TITLE
Need base path in option

### ISSUE THREAD

**Issue by AlanSmithey** [meeroslav/gulp-inject-partials#2]
Hi
This tool is pretty good, but it needs an option to add base path to components directory.
Something like this:
### option parameter

`{path: 'src/components'}`
### inside index.html

`<## _component_name.html>
</##>`
### resultative path compiled to

`src/components/_component_name.html`

**Comment by meeroslav** [comment]
@AlanSmithey nice to know you like it and use it. I'll do my best to implement this extension in the upcoming days.

**Comment by meeroslav** [comment]
@AlanSmithey Please find requested parameter as `prefix`.  It has two use-cases:

### 1. Common path segment:

For **configuration**:
`{prefix: 'my/url/prefix/'}`

And **markup**:
`<## component_name.html> </##>`

Result **path** would be:
`my/url/prefix/component_name.html`

### 2. Filename prefix:

For **configuration**:
`{prefix: '_partial_'}`

Result **path** would be:
`_partial_component_name.html`
