### ISSUE TITLE
On Error, exits the gulp execution

### ISSUE THREAD

**Issue by anulal-s** [meeroslav/gulp-inject-partials#3]
```
        .pipe(injectPartials({
            'removeTags': true,
            'quiet': !watchMode
        }).on('error', function(e) {
            util.log(util.colors.red(util.colors.bold('ERROR: Failed to inject partials')));
            util.log(util.colors.red(util.colors.bold(e.message)));
        }))

```
If any file is missing, the gulp stops the execution.

```
$ gulp
[15:28:30] ERROR: Failed to inject partials
[15:28:30] footer.html not found.
$
```
Is there any option to continue the execution of gulp, even if any of the partial file is not available. Ignore the missing partial and continue execution displaying the error.

**Comment by meeroslav** [comment]
This is considered as invalid state of the application so although implementation of this is possible, I would not suggest to use it in the real-life applications.

**Comment by anulal-s** [comment]
@meeroslav applications on development stage creates error, if we catch this error, the npm wont exit and not required to start the npm again. which may be time consuming when each files goes through multiple time consuming pipe/actions. for example [critical css](https://github.com/addyosmani/critical)

**Comment by meeroslav** [comment]
@anulal-s I will look into it as soon as possible. Sorry for the delay

**Comment by frkosk** [comment]
Hello guys, let me contribute.

You need a simple function like this one:

```javascript
function swallowError (error) {

  // If you want details of the error in the console
  console.log(error.toString())

  this.emit('end')
}
```

And add to the task: 

```javascript
gulp.task('html', function () {
  return gulp.src('src/pages/*.html')
           .pipe(injectPartials())
           **.on('error', swallowError)**
           .pipe(gulp.dest('./src'));
});
```

More discussions on [https://stackoverflow.com/a/23973536/1705724](https://stackoverflow.com/a/23973536/1705724)
