### ISSUE TITLE
Injecting fails for one particular partial, not others

### ISSUE THREAD

**Issue by melanieseltzer** [meeroslav/gulp-inject-partials#8]
I'm encountering a weird bug. 

I have three injects in a haml file sitting in a sub-folder.

**/test-directory/index.haml:**

```
!!! 5
%html
  %head
    %meta(charset="utf-8")
    %meta(content="IE=edge,chrome=1" http-equiv="X-UA-Compatible")
    %meta(name="viewport" content="width=device-width")

    %title Haml Template Sub-page
    %meta(name="description" content="")
    %meta(name="keywords" content="")

    %meta(name="robots" content="index, follow")

    <!-- partial:../partials/_head.html -->
    <!-- partial -->

  %body
    <!-- partial:../partials/_header.html -->
    <!-- partial -->

    %section
      %h1 This is a subpage!
      %img(src="/img/temp.jpg" alt="Michael Scott")

    <!-- partial:../partials/_footer.html -->
    <!-- partial -->
```

_footer.html is failing to inject, but it's inconsistent. Sometimes it works, sometimes it doesn't. I've spent two hours trying to nail down a pattern to what's causing it to fail, but I've not been able to conclusively say.

Interestingly, the footer partial in the root index.html always injects. It's only /test-directory/index.html that is not loading the footer partial. I thought perhaps the partial contents can't find a certain js file, but everything is there. And since it works on and off/not throwing an error... it's probably not the js files?

**_footer.haml partial contents**

```
%footer
  This is a footer!

<!--build:js /js/all.min.js -->
%script(src="/lib/jquery/dist/jquery.js")
%script(src="/js/app.js")
<!-- endbuild -->

```

**/test-directory/index.html output after haml build/inject is run:**

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
  <meta name="viewport" content="width=device-width" />
  <title>Haml Template Sub-page</title>
  <meta name="description" />
  <meta name="keywords" />
  <meta name="robots" content="index, follow" />
  <!-- partial:../partials/_head.html -->
  <!--build:css /css/all.min.css -->
<link rel="stylesheet" href="/css/styles.css" />
<!-- endbuild -->
  <!-- partial -->
</head>

<body>
  <!-- partial:../partials/_header.html -->
  <header>This is a header!
  <nav>This is a navigation bar!</nav>
</header>
  <!-- partial -->
  <section>
    <h1>This is a subpage!</h1><img src="/img/temp.jpg" alt="Michael Scott" /></section>
  <!-- partial:../partials/_footer.html -->
  
  <!-- partial -->
</body>

</html>
```

Head and header partials inject just fine, footer partial fails to load but comments are still there.

**Gulp task**

```
// Inject: Partials
// Inject all the html partials
gulp.task('inject:partials', ['compile:haml'], function () {
  return gulp.src(paths.html.src)
    .pipe(injectpartials())
    .pipe(gulp.dest(paths.html.build));
});
```

Am I missing something here? Bad syntax somewhere, some rule I'm not aware of?

[The repo](https://github.com/melanieseltzer/gulp-haml-boilerplate), for reference.

**Comment by meeroslav** [comment]
Hi @melanieseltzer, sorry for delay. 

Based on your repo I guess you've moved on from `gulp-inject-partials`.

If you still need help with this, please let me know, otherwise your code excerpt seems legit so without deep investigation I cannot say why the footer loading would fail.

**Comment by melanieseltzer** [comment]
No worries! Yes, I have switched to using Pug which has its own includes, so I no longer need to use a Gulp plugin for partial injection.

I feel like the above issue was caused by something bad in my Gulp process, not anything to do with the plugin. I remember before switching entirely to Pug, I tried another inject plugin and at first that was presenting the same issue. But then I tweaked things and got that other plugin working. 

So I feel like you can consider this issue closed, due to error on my part. Thank you for following up 😄
